---
conditions: v1
dist: xenial

git:
  depth: 200

services:
  - docker

language: python

branches:
  only:
    - master
    - /[0-9]+\.[0-9]+\.[0-9]+(.*)?$/

cache:
  - pip
  - directories:
      - "node_modules"
      - $HOME/.cache
os:
  - linux
before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - pip install tox-venv tox-tags
jobs:
  fast_finish: true
  include:
    - name: lint,py37,distros
      env: TOXENV=lint,py37,distros
      python: "3.7"
    - name: py35
      python: "3.5"
      env: TOXENV=py35
    - name: py36
      python: "3.6"
      env: TOXENV=py36
    - name: py38
      python: "3.8-dev"
      env: TOXENV=py38
    - name: py27
      python: "2.7"
      env: TOXENV=py27
    - stage: deploy
      name: deploy
      if: tag IS present AND type != cron
      env: TOXENV=upload
script:
  # https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-353342526
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - python -m tox
  - kill %1

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=1
    - TRAVIS_NODE_VERSION="v8.11.3"
