# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

# mandatory for ubi8 image which does not defaults to root
USER root

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
RUN echo "export {{ var }}={{ value }}" >> /etc/environment
{% endif %}
{% endfor %}
{% endif %}

CMD ["sh", "-c", "while true; do sleep 10000; done"]
